[api]
enabled = true

[functions.posts]
verify_jwt = false

[functions.votes]
verify_jwt = false

[functions.reports]
verify_jwt = false

[functions.auth]
verify_jwt = false

[functions.me]
verify_jwt = false

[functions.moderation-reports]
verify_jwt = false

[functions.moderation-comment-status]
verify_jwt = false

[functions.moderation-ban-user]
verify_jwt = false
